import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/styles/styles.css",
    "src/ui/accordion/index.ts",
    "src/ui/alert/index.ts",
    "src/ui/alert-dialog/index.ts",
    "src/ui/avatar/index.ts",
    "src/ui/badge/index.ts",
    "src/ui/bar-chart/index.ts",
    "src/ui/base-table/index.ts",
    "src/ui/button/index.ts",
    "src/ui/calendar/index.ts",
    "src/ui/card/index.ts",
    "src/ui/chart/index.ts",
    "src/ui/checkbox/index.ts",
    "src/ui/command/index.ts",
    "src/ui/custom-select/index.ts",
    "src/ui/DateCalendar/index.ts",
    "src/ui/DateField/index.ts",
    "src/ui/DateOfBirthSelector/index.ts",
    "src/ui/DateRangePicker/index.ts",
    "src/ui/dialog/index.ts",
    "src/ui/DobCalendar/index.ts",
    "src/ui/dropdown-menu/index.ts",
    "src/ui/form/index.ts",
    "src/ui/GetScrollAlert/index.ts",
    "src/ui/hover-card/index.ts",
    "src/ui/input/index.ts",
    "src/ui/label/index.ts",
    "src/ui/MultiLingualInputs/index.ts",
    "src/ui/multi-select/index.ts",
    "src/ui/navigation-menu/index.ts",
    "src/ui/popover/index.ts",
    "src/ui/radioButtonCard/index.ts",
    "src/ui/radio-group/index.ts",
    "src/ui/RadioGroupContext/index.ts",
    "src/ui/RouteChangeAlertPopUp/index.ts",
    "src/ui/scroll-area/index.ts",
    "src/ui/select/index.ts",
    "src/ui/SelectCommand/index.ts",
    "src/ui/separator/index.ts",
    "src/ui/sheet/index.ts",
    "src/ui/sidebar/index.ts",
    "src/ui/SlashIcon/index.ts",
    "src/ui/SortingArrows/index.ts",
    "src/ui/switch/index.ts",
    "src/ui/table/index.ts",
    "src/ui/tabs/index.ts",
    "src/ui/text/index.ts",
    "src/ui/textarea/index.ts",
    "src/ui/TextTags/index.ts",
    "src/ui/TiptapEditor/index.ts",
    "src/ui/TiptapExtensions/index.ts",
    "src/ui/TipTapToolbar/index.ts",
    "src/ui/tooltip/index.ts",
    "src/ui/vertical-bar-chart/index.ts",
  ],
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: false,
  target: "es2020",
  clean: false,
  splitting: true,
  outDir: "dist",
  external: [
    "react",
    "react-dom",
    "next",
    "next/router",
    "next/image",
    "react-hook-form",
    "@radix-ui/react-accordion",
    "@radix-ui/react-alert-dialog",
    "@radix-ui/react-avatar",
    "@radix-ui/react-checkbox",
    "@radix-ui/react-dialog",
    "@radix-ui/react-dropdown-menu",
    "@radix-ui/react-hover-card",
    "@radix-ui/react-icons",
    "@radix-ui/react-label",
    "@radix-ui/react-navigation-menu",
    "@radix-ui/react-popover",
    "@radix-ui/react-radio-group",
    "@radix-ui/react-scroll-area",
    "@radix-ui/react-select",
    "@radix-ui/react-separator",
    "@radix-ui/react-slot",
    "@radix-ui/react-switch",
    "@radix-ui/react-tabs",
    "@radix-ui/react-tooltip",
    "@tanstack/react-table",
    "@tiptap/core",
    "@tiptap/extension-character-count",
    "@tiptap/extension-color",
    "@tiptap/extension-image",
    "@tiptap/extension-link",
    "@tiptap/extension-text-align",
    "@tiptap/extension-text-style",
    "@tiptap/extension-underline",
    "@tiptap/pm",
    "@tiptap/react",
    "@tiptap/starter-kit",
    "class-variance-authority",
    "classnames",
    "clsx",
    "cmdk",
    "date-fns",
    "dayjs",
    "lucide-react",
    "prop-types",
    "react-day-picker",
    "react-toastify",
    "recharts",
    "tailwind-merge",
    "zustand"
  ],
  loader: {
    ".svg": "dataurl"
  },
  esbuildOptions(options) {
    options.chunkNames = "chunks/[name]-[hash]";
  }
});
