import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/styles/styles.css",
    "src/ui/accordion.tsx",
    "src/ui/alert-dialog.tsx",
    "src/ui/alert.tsx",
    "src/ui/avatar.tsx",
    "src/ui/badge.tsx",
    "src/ui/bar-chart.tsx",
    "src/ui/button.tsx",
    "src/ui/calendar.tsx",
    "src/ui/card.tsx",
    "src/ui/chart.tsx",
    "src/ui/checkbox.tsx",
    "src/ui/command.tsx",
    "src/ui/CourseDiscountCodeInput.tsx",
    "src/ui/custom-select.tsx",
    "src/ui/DateCalendar.tsx",
    "src/ui/DateField.tsx",
    "src/ui/DateOfBirthSelector.tsx",
    "src/ui/DateRangePicker.tsx",
    "src/ui/dialog.tsx",
    "src/ui/DiscountCodeInput.tsx",
    "src/ui/DobCalendar.tsx",
    "src/ui/dropdown-menu.tsx",
    "src/ui/form.tsx",
    "src/ui/hover-card.tsx",
    "src/ui/input.tsx",
    "src/ui/label.tsx",
    "src/ui/multi-select.tsx",
    "src/ui/MultiLingualInputs.tsx",
    "src/ui/navigation-menu.tsx",
    "src/ui/popover.tsx",
    "src/ui/radio-group.tsx",
    "src/ui/radioButtonCard.tsx",
    "src/ui/RouteChangeAlertPopUp.tsx",
    "src/ui/scroll-area.tsx",
    "src/ui/select.tsx",
    "src/ui/SelectCommand.tsx",
    "src/ui/separator.tsx",
    "src/ui/sheet.tsx",
    "src/ui/sidebar.tsx",
    "src/ui/SlashIcon.tsx",
    "src/ui/SortingArrows.tsx",
    "src/ui/switch.tsx",
    "src/ui/table.tsx",
    "src/ui/tabs.tsx",
    "src/ui/text.tsx",
    "src/ui/textarea.tsx",
    "src/ui/TextTags.tsx",
    "src/ui/TiptapEditor.tsx",
    "src/ui/TipTapToolbar.tsx",
    "src/ui/tooltip.tsx",
    "src/ui/vertical-bar-chart.tsx",
    "src/ui/RadioGroupContext/RadioGroupContext.tsx",
    "src/ui/TiptapExtensions/font-size.ts",
    "src/components/course/findCourse/BaseTable.tsx"
  ],
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: true,
  target: "es2020",
  clean: false,
  splitting: false,
  outDir: "dist",
  external: ["react", "react-dom", "next", "next/router", "next/image", "react-hook-form"],
  loader: {
    ".svg": "dataurl"
  },
  esbuildOptions(options) {
    options.chunkNames = "chunks/[name]-[hash]";
  }
});
