import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/styles/styles.css",
    "src/ui/accordion.tsx",
    "src/ui/alert-dialog.tsx",
    "src/ui/alert.tsx",
    "src/ui/avatar.tsx",
    "src/ui/badge.tsx",
    "src/ui/bar-chart.tsx",
    "src/ui/button.tsx",
    "src/ui/calendar.tsx",
    "src/ui/card.tsx",
    "src/ui/chart.tsx",
    "src/ui/checkbox.tsx",
    "src/ui/command.tsx",
    "src/ui/CourseDiscountCodeInput.tsx",
    "src/ui/custom-select.tsx",
    "src/ui/DateCalendar.tsx",
    "src/ui/DateField.tsx",
    "src/ui/DateOfBirthSelector.tsx",
    "src/ui/DateRangePicker.tsx",
    "src/ui/dialog.tsx",
    "src/ui/DiscountCodeInput.tsx",
    "src/ui/DobCalendar.tsx",
    "src/ui/dropdown-menu.tsx",
    "src/ui/form.tsx",
    "src/ui/hover-card.tsx",
    "src/ui/input.tsx",
    "src/ui/label.tsx",
    "src/ui/multi-select.tsx",
    "src/ui/MultiLingualInputs.tsx",
    "src/ui/navigation-menu.tsx",
    "src/ui/popover.tsx",
    "src/ui/radio-group.tsx",
    "src/ui/radioButtonCard.tsx",
    "src/ui/RouteChangeAlertPopUp.tsx",
    "src/ui/scroll-area.tsx",
    "src/ui/select.tsx",
    "src/ui/SelectCommand.tsx",
    "src/ui/separator.tsx",
    "src/ui/sheet.tsx",
    "src/ui/sidebar.tsx",
    "src/ui/SlashIcon.tsx",
    "src/ui/SortingArrows.tsx",
    "src/ui/switch.tsx",
    "src/ui/table.tsx",
    "src/ui/tabs.tsx",
    "src/ui/text.tsx",
    "src/ui/textarea.tsx",
    "src/ui/TextTags.tsx",
    "src/ui/TiptapEditor.tsx",
    "src/ui/TipTapToolbar.tsx",
    "src/ui/tooltip.tsx",
    "src/ui/vertical-bar-chart.tsx",
    "src/ui/RadioGroupContext/RadioGroupContext.tsx",
    "src/ui/TiptapExtensions/font-size.ts",
    "src/components/course/findCourse/BaseTable.tsx"
  ],
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: false,
  target: "es2020",
  clean: false,
  splitting: true,
  outDir: "dist",
  external: [
    "react",
    "react-dom",
    "next",
    "next/router",
    "next/image",
    "react-hook-form",
    "@radix-ui/react-accordion",
    "@radix-ui/react-alert-dialog",
    "@radix-ui/react-avatar",
    "@radix-ui/react-checkbox",
    "@radix-ui/react-dialog",
    "@radix-ui/react-dropdown-menu",
    "@radix-ui/react-hover-card",
    "@radix-ui/react-icons",
    "@radix-ui/react-label",
    "@radix-ui/react-navigation-menu",
    "@radix-ui/react-popover",
    "@radix-ui/react-radio-group",
    "@radix-ui/react-scroll-area",
    "@radix-ui/react-select",
    "@radix-ui/react-separator",
    "@radix-ui/react-slot",
    "@radix-ui/react-switch",
    "@radix-ui/react-tabs",
    "@radix-ui/react-tooltip",
    "@tanstack/react-table",
    "@tiptap/core",
    "@tiptap/extension-character-count",
    "@tiptap/extension-color",
    "@tiptap/extension-image",
    "@tiptap/extension-link",
    "@tiptap/extension-text-align",
    "@tiptap/extension-text-style",
    "@tiptap/extension-underline",
    "@tiptap/pm",
    "@tiptap/react",
    "@tiptap/starter-kit",
    "class-variance-authority",
    "classnames",
    "clsx",
    "cmdk",
    "date-fns",
    "dayjs",
    "lucide-react",
    "prop-types",
    "react-day-picker",
    "react-toastify",
    "recharts",
    "tailwind-merge",
    "zustand"
  ],
  loader: {
    ".svg": "dataurl"
  },
  esbuildOptions(options) {
    options.chunkNames = "chunks/[name]-[hash]";
  }
});
