// Form names to validate manual registration
export const ManualRegistrationFormNames = {
  program_data: "program_data",
  contact_obj: "contact_obj",
  view_contact_obj: "view_contact_obj",
  contact_id: "contact_id",
  tenant_id: "tenant_id",
  registration_date: "registration_date",
  fee_level_obj: "fee_level_obj",
  fee_level_id: "fee_level_id",
  course_fee: "course_fee",
  participant_attendance_status: "participant_attendance_status",
  discount_code: "discount_code",
  discounted_amount: "discounted_amount",
  discount_code_description: "discount_code_description",
  organization_discount_amount: "organization_discount_amount",
  accommodation_discount_amount: "accommodation_discount_amount",
  expense_discount_amount: "expense_discount_amount",
  participant_student_id: "participant_student_id",
  participant_senior_id: "participant_senior_id",
  student_issuing_authority: "student_issuing_authority",
  senior_issuing_authority: "senior_issuing_authority",
  expiration_date: "expiration_date",
  repeater_course_country: "repeater_course_country",
  repeater_course_state: "repeater_course_state",
  repeater_course_city: "repeater_course_city",
  repeater_course_teacher: "repeater_course_teacher",
  course_place: "course_place",
  repeater_course_date: "repeater_course_date",
  accommodation_type_obj: "accommodation_type_obj",
  accommodation_type_id: "accommodation_type_id",
  accommodation_fee: "accommodation_fee",
  accommodation_snore: "accommodation_snore",
  roommate_snore: "roommate_snore",
  is_sending_payment_link: "is_sending_payment_link",
  total_fee: "total_fee",
  payment_date: "payment_date",
  payment_method: "payment_method",
  payment_method_id: "payment_method_id",
  payment_details: "payment_details",
  bank_name: "bank_name",
  transaction_id: "transaction_id",
  cheque_number: "cheque_number",
  payment_transaction_status: "payment_transaction_status",
  payment_method_payment_link_id: "payment_method_payment_link_id",
  upload_receipt_url: "upload_receipt_url",
  upload_receipt_file_name: "upload_receipt_file_name",
  student_id_card_attachment: "student_id_card_attachment",
  tax_percentage: "tax_percentage",
  tax_display_label: "tax_display_label",
  is_tax_enabled: "is_tax_enabled",
  organization_code: "organization_code",
  ppa_and_health_declaration_version: "ppa_and_health_declaration_version",
  is_sponsor_by_business_enable: "is_sponsor_by_business_enable",
  collect_doctor_details_in_youth_course_reg:
    "collect_doctor_details_in_youth_course_reg",
  is_payment_status_for_obt_editable_by_na_and_fa_for_course:
    "is_payment_status_for_obt_editable_by_na_and_fa_for_course",
  is_offline_payment_receipts_upload_enabled_for_course:
    "is_offline_payment_receipts_upload_enabled_for_course",
  sponsor_by_company: "sponsor_by_company",
  company_name: "company_name",
  company_vat: "company_vat",
  company_address: "company_address",
  company_country_id: "company_country_id",
  company_email: "company_email",
  roommate_preferences_1: "roommate_preferences_1",
  roommate_preferences_2: "roommate_preferences_2",
  roommate_preferences_3: "roommate_preferences_3",
  child_first_name: "child_first_name",
  child_last_name: "child_last_name",
  child_date_of_birth: "child_date_of_birth",
  child_gender: "child_gender",
  child_email: "child_email",
  special_concerns_for_child: "special_concerns_for_child",
  doctor_contact_full_name: "doctor_contact_full_name",
  doctor_contact_phone: "doctor_contact_phone",
  doctor_contact_email: "doctor_contact_email",
  doctor_phone_country_code: "doctor_phone_country_code",
  emergency1_contact_full_name: "emergency1_contact_full_name",
  emergency1_contact_phone: "emergency1_contact_phone",
  emergency1_contact_phone_country_code:
    "emergency1_contact_phone_country_code",
  expense_fee: "expense_fee",
  child_health_condition: "child_health_condition",
  is_duplicate_registration_with_email: "is_duplicate_registration_with_email",
  is_duplicate_registration_without_email:
    "is_duplicate_registration_without_email",
  is_child_have_any_health_problems: "is_child_have_any_health_problems",
  is_offline_payment_option_enable: "is_offline_payment_option_enable",
  is_online_payment_option_enable: "is_online_payment_option_enable",
  deposit_option: "deposit_option",
  deposit_pay_amount: "deposit_pay_amount",
  is_deposits_enabled: "is_deposits_enabled",
  deposits_accepting_days_from_start_date:
    "deposits_accepting_days_from_start_date",
  deposit_text_on_registration_form: "deposit_text_on_registration_form",
  org_product_fee_level_config: "org_product_fee_level_config",
  deposit_total: "deposit_total",
  fee_level_is_deposit_enabled: "fee_level_is_deposit_enabled",
  remaining_amount_to_be_pay: "remaining_amount_to_be_pay",
  deposit_type: "deposit_type",
  org_product_fee_config: "org_product_fee_config",
  fee_level_payment_type_deposit_only: "fee_level_payment_type_deposit_only",
  organization_id: "organization_id",
  preferred_language: "preferred_language",
  country_code: "country_code",
  main_deposit_fee: "main_deposit_fee",
  deposit_fee_level_matching: "deposit_fee_level_matching",
  //These two are used for Intuition Program Registrations
  email_id_for_app_access: "email_id_for_app_access",
  use_email_for_app_access: "use_email_for_app_access",
  registration_country_id: "registration_country_id",
  is_accommodation_needed: "is_accommodation_needed",
  is_food_needed: "is_food_needed",
  is_registration_accommodation_needed_option_enable:
    "is_registration_accommodation_needed_option_enable",
  is_visitor_tax_collected: "is_visitor_tax_collected",
  is_food_fee_collected: "is_food_fee_collected",
  food_fee_sub_total: "food_fee_sub_total",
  food_fee_tax: "food_fee_tax",
  food_fee_total_amount: "food_fee_total_amount",
  visitor_tax_total_amount: "visitor_tax_total_amount",
  food_discount_amount: "food_discount_amount",
  visitor_tax_discount_amount: "visitor_tax_discount_amount",
  is_food_fee_needed_option_enable: "is_food_fee_needed_option_enable",
  food_fee_day_count: "food_fee_day_count",
  agency_note: "agency_note",
  is_room_booking_system_enable: "is_room_booking_system_enable",
  registration_allowed_countries: "registration_allowed_countries",
  agency_name: "agency_name",
  is_vat_obligated: "is_vat_obligated",
  upload_student_id_card_url: "upload_student_id_card_url",
  upload_student_id_card_file_name: "upload_student_id_card_file_name",
};
